"""add missing fields and constraints

Revision ID: 41a7a4f3b3e6
Revises: 92f2671068a4
Create Date: 2026-01-24 22:55:56.357928

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '41a7a4f3b3e6'
down_revision: str | None = '92f2671068a4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('balance_snapshots_account_id_fkey'), 'balance_snapshots', type_='foreignkey')
    op.create_foreign_key(None, 'balance_snapshots', 'exchange_accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('equity_curves_run_id_fkey'), 'equity_curves', type_='foreignkey')
    op.create_foreign_key(None, 'equity_curves', 'strategy_runs', ['run_id'], ['id'], ondelete='CASCADE')
    op.add_column('orders', sa.Column('exchange', sa.String(length=32), nullable=False))
    op.drop_constraint(op.f('orders_account_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_run_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'exchange_accounts', ['account_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'orders', 'strategy_runs', ['run_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('risk_triggers_run_id_fkey'), 'risk_triggers', type_='foreignkey')
    op.drop_constraint(op.f('risk_triggers_rule_id_fkey'), 'risk_triggers', type_='foreignkey')
    op.create_foreign_key(None, 'risk_triggers', 'strategy_runs', ['run_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'risk_triggers', 'risk_rules', ['rule_id'], ['id'], ondelete='CASCADE')
    op.add_column('strategy_runs', sa.Column('slippage', sa.Numeric(precision=10, scale=8), nullable=True))
    op.add_column('strategy_runs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('strategy_runs_account_id_fkey'), 'strategy_runs', type_='foreignkey')
    op.drop_constraint(op.f('strategy_runs_strategy_id_fkey'), 'strategy_runs', type_='foreignkey')
    op.create_foreign_key(None, 'strategy_runs', 'exchange_accounts', ['account_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'strategy_runs', 'strategies', ['strategy_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('trades_order_id_fkey'), 'trades', type_='foreignkey')
    op.create_foreign_key(None, 'trades', 'orders', ['order_id'], ['id'], ondelete='CASCADE')

    # Create TimescaleDB hypertables
    op.execute("SELECT create_hypertable('klines', 'time', if_not_exists => TRUE);")
    op.execute("SELECT create_hypertable('equity_curves', 'time', if_not_exists => TRUE);")
    op.execute("SELECT create_hypertable('balance_snapshots', 'time', if_not_exists => TRUE);")

    # Add compression policies (compress after 7 days)
    op.execute("""
        ALTER TABLE klines SET (
            timescaledb.compress,
            timescaledb.compress_segmentby = 'exchange, symbol, timeframe'
        );
    """)
    op.execute("SELECT add_compression_policy('klines', INTERVAL '7 days', if_not_exists => TRUE);")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.create_foreign_key(op.f('trades_order_id_fkey'), 'trades', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'strategy_runs', type_='foreignkey')
    op.drop_constraint(None, 'strategy_runs', type_='foreignkey')
    op.create_foreign_key(op.f('strategy_runs_strategy_id_fkey'), 'strategy_runs', 'strategies', ['strategy_id'], ['id'])
    op.create_foreign_key(op.f('strategy_runs_account_id_fkey'), 'strategy_runs', 'exchange_accounts', ['account_id'], ['id'])
    op.drop_column('strategy_runs', 'updated_at')
    op.drop_column('strategy_runs', 'slippage')
    op.drop_constraint(None, 'risk_triggers', type_='foreignkey')
    op.drop_constraint(None, 'risk_triggers', type_='foreignkey')
    op.create_foreign_key(op.f('risk_triggers_rule_id_fkey'), 'risk_triggers', 'risk_rules', ['rule_id'], ['id'])
    op.create_foreign_key(op.f('risk_triggers_run_id_fkey'), 'risk_triggers', 'strategy_runs', ['run_id'], ['id'])
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_run_id_fkey'), 'orders', 'strategy_runs', ['run_id'], ['id'])
    op.create_foreign_key(op.f('orders_account_id_fkey'), 'orders', 'exchange_accounts', ['account_id'], ['id'])
    op.drop_column('orders', 'exchange')
    op.drop_constraint(None, 'equity_curves', type_='foreignkey')
    op.create_foreign_key(op.f('equity_curves_run_id_fkey'), 'equity_curves', 'strategy_runs', ['run_id'], ['id'])
    op.drop_constraint(None, 'balance_snapshots', type_='foreignkey')
    op.create_foreign_key(op.f('balance_snapshots_account_id_fkey'), 'balance_snapshots', 'exchange_accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###
