"""add trade sync fields

Revision ID: 796dbf28b37b
Revises: b3f1a2c4d5e7
Create Date: 2026-03-20 10:38:54.973354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '796dbf28b37b'
down_revision: Union[str, None] = 'b3f1a2c4d5e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('corrections', sa.JSON(), nullable=True))
    op.create_index('idx_orders_exchange_oid', 'orders', ['exchange_oid'], unique=False)
    op.create_index('idx_orders_symbol', 'orders', ['symbol'], unique=False)
    op.add_column('trades', sa.Column('taker_or_maker', sa.String(length=8), nullable=True))
    op.alter_column('trades', 'fill_source',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=16),
               existing_nullable=True)
    op.create_index(
        "ix_trades_exchange_tid_unique",
        "trades",
        ["exchange_tid"],
        unique=True,
        postgresql_where=sa.text("exchange_tid IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_trades_exchange_tid_unique", table_name="trades")
    op.alter_column('trades', 'fill_source',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    op.drop_column('trades', 'taker_or_maker')
    op.drop_index('idx_orders_symbol', table_name='orders')
    op.drop_index('idx_orders_exchange_oid', table_name='orders')
    op.drop_column('orders', 'corrections')
    # ### end Alembic commands ###
