"""create initial tables

Revision ID: 92f2671068a4
Revises:
Create Date: 2026-01-24 22:39:57.882456

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92f2671068a4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_accounts',
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('api_key_enc', sa.LargeBinary(), nullable=False),
    sa.Column('api_secret_enc', sa.LargeBinary(), nullable=False),
    sa.Column('passphrase_enc', sa.LargeBinary(), nullable=True),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('testnet', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'name', name='uq_exchange_account_name')
    )
    op.create_index('idx_exchange_accounts_exchange', 'exchange_accounts', ['exchange'], unique=False)
    op.create_table('klines',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.PrimaryKeyConstraint('time', 'exchange', 'symbol', 'timeframe')
    )
    op.create_index('idx_klines_symbol_time', 'klines', ['exchange', 'symbol', 'timeframe', 'time'], unique=False)
    op.create_table('risk_rules',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategies',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('params_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_strategies_status', 'strategies', ['status'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('module', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_system_logs_created', 'system_logs', ['created_at'], unique=False)
    op.create_index('idx_system_logs_level', 'system_logs', ['level'], unique=False)
    op.create_table('watchlist',
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'symbol', name='uq_watchlist_exchange_symbol')
    )
    op.create_table('balance_snapshots',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('free', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('locked', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('usd_value', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['exchange_accounts.id'], ),
    sa.PrimaryKeyConstraint('time', 'account_id', 'currency')
    )
    op.create_table('strategy_runs',
    sa.Column('strategy_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('backtest_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('backtest_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('initial_capital', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('commission_rate', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('process_id', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['exchange_accounts.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_strategy_runs_mode', 'strategy_runs', ['mode'], unique=False)
    op.create_index('idx_strategy_runs_status', 'strategy_runs', ['status'], unique=False)
    op.create_index('idx_strategy_runs_strategy', 'strategy_runs', ['strategy_id'], unique=False)
    op.create_table('equity_curves',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('equity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('cash', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('position_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['strategy_runs.id'], ),
    sa.PrimaryKeyConstraint('time', 'run_id')
    )
    op.create_table('orders',
    sa.Column('run_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('exchange_oid', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('filled', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['exchange_accounts.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['strategy_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_account', 'orders', ['account_id'], unique=False)
    op.create_index('idx_orders_created', 'orders', ['created_at'], unique=False)
    op.create_index('idx_orders_run', 'orders', ['run_id'], unique=False)
    op.create_index('idx_orders_status', 'orders', ['status'], unique=False)
    op.create_table('risk_triggers',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rule_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('run_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['risk_rules.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['strategy_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_risk_triggers_rule_id', 'risk_triggers', ['rule_id'], unique=False)
    op.create_index('idx_risk_triggers_run_id', 'risk_triggers', ['run_id'], unique=False)
    op.create_index('idx_risk_triggers_time', 'risk_triggers', ['time'], unique=False)
    op.create_table('trades',
    sa.Column('order_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('exchange_tid', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('fee', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('fee_currency', sa.String(length=16), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trades_order', 'trades', ['order_id'], unique=False)
    op.create_index('idx_trades_timestamp', 'trades', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trades_timestamp', table_name='trades')
    op.drop_index('idx_trades_order', table_name='trades')
    op.drop_table('trades')
    op.drop_index('idx_risk_triggers_time', table_name='risk_triggers')
    op.drop_index('idx_risk_triggers_run_id', table_name='risk_triggers')
    op.drop_index('idx_risk_triggers_rule_id', table_name='risk_triggers')
    op.drop_table('risk_triggers')
    op.drop_index('idx_orders_status', table_name='orders')
    op.drop_index('idx_orders_run', table_name='orders')
    op.drop_index('idx_orders_created', table_name='orders')
    op.drop_index('idx_orders_account', table_name='orders')
    op.drop_table('orders')
    op.drop_table('equity_curves')
    op.drop_index('idx_strategy_runs_strategy', table_name='strategy_runs')
    op.drop_index('idx_strategy_runs_status', table_name='strategy_runs')
    op.drop_index('idx_strategy_runs_mode', table_name='strategy_runs')
    op.drop_table('strategy_runs')
    op.drop_table('balance_snapshots')
    op.drop_table('watchlist')
    op.drop_index('idx_system_logs_level', table_name='system_logs')
    op.drop_index('idx_system_logs_created', table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index('idx_strategies_status', table_name='strategies')
    op.drop_table('strategies')
    op.drop_table('risk_rules')
    op.drop_index('idx_klines_symbol_time', table_name='klines')
    op.drop_table('klines')
    op.drop_index('idx_exchange_accounts_exchange', table_name='exchange_accounts')
    op.drop_table('exchange_accounts')
    # ### end Alembic commands ###
