#!/bin/bash
# Post-create script for Dev Container
# This script runs after the container is created

set -e

echo "🚀 Initializing Squant development environment..."

# Fix volume permissions (Docker named volumes are created as root)
echo "🔧 Fixing volume permissions..."
sudo chown -R vscode:vscode /home/vscode/.cache/uv 2>/dev/null || mkdir -p /home/vscode/.cache/uv
sudo chown -R vscode:vscode /home/vscode/.local/share/pnpm 2>/dev/null || true
sudo chown -R vscode:vscode /workspaces/Squant/.venv 2>/dev/null || true
sudo chown -R vscode:vscode /workspaces/Squant/frontend/node_modules 2>/dev/null || true

# Change to workspace directory
cd /workspaces/Squant

# Install Python dependencies with uv
echo "📦 Installing Python dependencies..."
uv sync

# Install frontend dependencies
echo "📦 Installing frontend dependencies..."
cd frontend
pnpm install
cd ..

# Create .env.test.local from template if it doesn't exist
if [ ! -f .env.test.local ]; then
    echo "📝 Creating .env.test.local from template..."
    cp .env.test.local.example .env.test.local
    echo "NOTE: Edit .env.test.local to add exchange API credentials for integration tests"
fi

# Create .env file if it doesn't exist
if [ ! -f .env ]; then
    echo "📝 Creating .env file from template..."
    cat > .env << 'EOF'
# Development environment configuration
# Generated by Dev Container post-create script

# Database
DATABASE_URL=postgresql+asyncpg://squant:devpassword@postgres:5432/squant

# Redis
REDIS_URL=redis://redis:6379/0

# Security (development only - change in production!)
SECRET_KEY=dev-secret-key-minimum-32-characters-long
ENCRYPTION_KEY=dev-encryption-key-32-chars-long!!

# Development settings
DEBUG=true
LOG_LEVEL=DEBUG

# Exchange settings
DEFAULT_EXCHANGE=okx
USE_CCXT_PROVIDER=true

# Exchange API credentials (add your testnet keys here)
# OKX_API_KEY=
# OKX_API_SECRET=
# OKX_PASSPHRASE=
# BINANCE_API_KEY=
# BINANCE_API_SECRET=
# BYBIT_API_KEY=
# BYBIT_API_SECRET=
EOF
fi

# Wait for database to be ready
echo "⏳ Waiting for database..."
until pg_isready -h postgres -U squant -d squant > /dev/null 2>&1; do
    sleep 1
done

# Run database migrations
echo "🗄️ Running database migrations..."
uv run alembic upgrade head

# Install pre-commit hooks
echo "🪝 Setting up pre-commit hooks..."
if [ -f .pre-commit-config.yaml ]; then
    uv run pre-commit install || true
fi

# Install Claude Code CLI (using native installer)
echo "🤖 Installing Claude Code CLI..."
sudo mkdir -p /home/vscode/.local/state /home/vscode/.local/bin /home/vscode/.cache/claude
sudo chown -R vscode:vscode /home/vscode/.local /home/vscode/.cache
curl -fsSL https://claude.ai/install.sh | bash || true
# Fix Claude config permissions and paths if mounted from host
if [ -d /home/vscode/.claude ]; then
    sudo chown -R vscode:vscode /home/vscode/.claude 2>/dev/null || true
    # Fix plugin marketplace paths (convert macOS paths to Linux paths)
    if [ -f /home/vscode/.claude/plugins/known_marketplaces.json ]; then
        sed -i 's|/Users/[^/]*/\.claude|/home/vscode/.claude|g' /home/vscode/.claude/plugins/known_marketplaces.json
    fi
fi

# Set Git safe directory
git config --global --add safe.directory /workspaces/Squant

echo ""
echo "✅ Development environment ready!"
echo ""
echo "Quick start commands:"
echo "  ./scripts/dev.sh backend    - Start backend server"
echo "  cd frontend && pnpm dev     - Start frontend dev server"
echo "  uv run pytest tests/unit -v - Run unit tests"
echo ""
