"""Pydantic schemas for request/response validation."""

from squant.schemas.account import (
    ConnectionTestResponse,
    CreateExchangeAccountRequest,
    ExchangeAccountListItem,
    ExchangeAccountResponse,
    UpdateExchangeAccountRequest,
)
from squant.schemas.backtest import (
    AvailableSymbolResponse,
    BacktestDetailResponse,
    BacktestListItem,
    BacktestMetrics,
    BacktestRunResponse,
    CheckDataRequest,
    CreateBacktestRequest,
    DataAvailabilityResponse,
    EquityCurvePoint,
    FillRecordResponse,
    RunBacktestRequest,
    TradeRecordResponse,
)
from squant.schemas.circuit_breaker import (
    CircuitBreakerEventResponse,
    CircuitBreakerStatusResponse,
    CloseAllPositionsRequest,
    CloseAllPositionsResponse,
    ResetCircuitBreakerResponse,
    RiskTriggerListItem,
    RiskTriggerResponse,
    TriggerCircuitBreakerRequest,
    TriggerCircuitBreakerResponse,
)
from squant.schemas.exchange import (
    BalanceItem,
    BalanceResponse,
    CancelOrderRequest,
    CandlestickItem,
    CandlestickResponse,
    OpenOrdersResponse,
    OrderResponse,
    PlaceOrderRequest,
    TickerResponse,
)
from squant.schemas.live_trading import (
    EmergencyCloseResponse,
    LiveOrderInfo,
    LivePositionInfo,
    LiveTradingListItem,
    LiveTradingRunResponse,
    LiveTradingStatusResponse,
    RiskConfigRequest,
    RiskStateResponse,
    StartLiveTradingRequest,
    StopLiveTradingRequest,
)
from squant.schemas.order import (
    CreateOrderRequest,
    ListOrdersRequest,
    OrderDetail,
    OrderListData,
    OrderStatsResponse,
    OrderWithTrades,
    SyncOrdersResponse,
    TradeDetail,
)
from squant.schemas.paper_trading import (
    PaperTradingListItem,
    PaperTradingRunResponse,
    PaperTradingStatusResponse,
    PendingOrderInfo,
    PositionInfo,
    StartPaperTradingRequest,
)
from squant.schemas.risk import (
    CreateRiskRuleRequest,
    RiskRuleListItem,
    RiskRuleResponse,
    ToggleRiskRuleRequest,
    UpdateRiskRuleRequest,
)
from squant.schemas.strategy import (
    CreateStrategyRequest,
    StrategyListItem,
    StrategyResponse,
    UpdateStrategyRequest,
    ValidateCodeRequest,
    ValidationResultResponse,
)
from squant.schemas.watchlist import (
    AddToWatchlistRequest,
    ReorderWatchlistItem,
    ReorderWatchlistRequest,
    WatchlistCheckResponse,
    WatchlistItemResponse,
)

__all__ = [
    # Exchange account schemas
    "CreateExchangeAccountRequest",
    "UpdateExchangeAccountRequest",
    "ExchangeAccountResponse",
    "ExchangeAccountListItem",
    "ConnectionTestResponse",
    # Exchange schemas
    "BalanceItem",
    "BalanceResponse",
    "CancelOrderRequest",
    "CandlestickItem",
    "CandlestickResponse",
    "OpenOrdersResponse",
    "OrderResponse",
    "PlaceOrderRequest",
    "TickerResponse",
    # Order management schemas
    "CreateOrderRequest",
    "ListOrdersRequest",
    "OrderDetail",
    "OrderListData",
    "OrderStatsResponse",
    "OrderWithTrades",
    "SyncOrdersResponse",
    "TradeDetail",
    # Strategy schemas
    "CreateStrategyRequest",
    "UpdateStrategyRequest",
    "ValidateCodeRequest",
    "ValidationResultResponse",
    "StrategyResponse",
    "StrategyListItem",
    # Risk schemas
    "CreateRiskRuleRequest",
    "UpdateRiskRuleRequest",
    "ToggleRiskRuleRequest",
    "RiskRuleResponse",
    "RiskRuleListItem",
    # Backtest schemas
    "RunBacktestRequest",
    "CreateBacktestRequest",
    "CheckDataRequest",
    "BacktestRunResponse",
    "BacktestListItem",
    "BacktestDetailResponse",
    "BacktestMetrics",
    "EquityCurvePoint",
    "TradeRecordResponse",
    "FillRecordResponse",
    "DataAvailabilityResponse",
    "AvailableSymbolResponse",
    # Watchlist schemas
    "AddToWatchlistRequest",
    "ReorderWatchlistItem",
    "ReorderWatchlistRequest",
    "WatchlistItemResponse",
    "WatchlistCheckResponse",
    # Paper trading schemas
    "StartPaperTradingRequest",
    "PaperTradingRunResponse",
    "PositionInfo",
    "PendingOrderInfo",
    "PaperTradingStatusResponse",
    "PaperTradingListItem",
    # Live trading schemas
    "RiskConfigRequest",
    "StartLiveTradingRequest",
    "LiveTradingRunResponse",
    "LivePositionInfo",
    "LiveOrderInfo",
    "RiskStateResponse",
    "LiveTradingStatusResponse",
    "LiveTradingListItem",
    "StopLiveTradingRequest",
    "EmergencyCloseResponse",
    # Circuit breaker schemas
    "TriggerCircuitBreakerRequest",
    "TriggerCircuitBreakerResponse",
    "CloseAllPositionsRequest",
    "CloseAllPositionsResponse",
    "CircuitBreakerStatusResponse",
    "ResetCircuitBreakerResponse",
    "RiskTriggerResponse",
    "RiskTriggerListItem",
    "CircuitBreakerEventResponse",
]
