"""add exchange_accounts table

Revision ID: d5e2e4381e3f
Revises: 379ceb2498af
Create Date: 2026-01-24 14:08:00.019326+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e2e4381e3f'
down_revision: Union[str, Sequence[str], None] = '379ceb2498af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.Enum('binance', 'okx', 'huobi', name='exchangetype'), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=False),
    sa.Column('api_secret', sa.String(length=500), nullable=False),
    sa.Column('passphrase', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_accounts_id'), 'exchange_accounts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchange_accounts_id'), table_name='exchange_accounts')
    op.drop_table('exchange_accounts')
    # ### end Alembic commands ###
