"""add market data and watchlist tables

Revision ID: 82bc6c0b93cc
Revises: d5e2e4381e3f
Create Date: 2026-01-24 14:57:29.348442+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82bc6c0b93cc'
down_revision: Union[str, Sequence[str], None] = 'd5e2e4381e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('timeframe', sa.String(length=20), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('open_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('quote_volume', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('trades_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='K线数据表'
    )
    op.create_index(op.f('ix_candles_exchange'), 'candles', ['exchange'], unique=False)
    op.create_index(op.f('ix_candles_id'), 'candles', ['id'], unique=False)
    op.create_index(op.f('ix_candles_open_time'), 'candles', ['open_time'], unique=False)
    op.create_index(op.f('ix_candles_symbol'), 'candles', ['symbol'], unique=False)
    op.create_index(op.f('ix_candles_timeframe'), 'candles', ['timeframe'], unique=False)
    op.create_table('user_watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='用户自选币种表'
    )
    op.create_index(op.f('ix_user_watchlist_id'), 'user_watchlist', ['id'], unique=False)
    op.create_index(op.f('ix_user_watchlist_symbol'), 'user_watchlist', ['symbol'], unique=False)
    op.create_index(op.f('ix_user_watchlist_user_id'), 'user_watchlist', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_watchlist_user_id'), table_name='user_watchlist')
    op.drop_index(op.f('ix_user_watchlist_symbol'), table_name='user_watchlist')
    op.drop_index(op.f('ix_user_watchlist_id'), table_name='user_watchlist')
    op.drop_table('user_watchlist')
    op.drop_index(op.f('ix_candles_timeframe'), table_name='candles')
    op.drop_index(op.f('ix_candles_symbol'), table_name='candles')
    op.drop_index(op.f('ix_candles_open_time'), table_name='candles')
    op.drop_index(op.f('ix_candles_id'), table_name='candles')
    op.drop_index(op.f('ix_candles_exchange'), table_name='candles')
    op.drop_table('candles')
    # ### end Alembic commands ###
