"""fix: 金融数据使用 Numeric 类型替代 Float

Revision ID: 379ceb2498af
Revises: abc2e4e2fcf3
Create Date: 2026-01-24 13:30:27.484619+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '379ceb2498af'
down_revision: Union[str, Sequence[str], None] = 'abc2e4e2fcf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=False)
    op.alter_column('orders', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=True)
    op.alter_column('strategy_executions', 'profit',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('strategy_executions', 'profit',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('orders', 'price',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('orders', 'quantity',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
